version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"   # React served at localhost:3000
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app   # so code updates reflect
